version: '3.8'

services:
  solarwatch:
    build: .
    container_name: solarwatch
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SolarWatch_connection=Server=http://localhost:1433;Database=SolarWatch;User Id=sa;Password=yourStrong(!)Password;Encrypt=false;
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    networks:
      - solarwatch-network

networks:
  solarwatch-network:
    driver: bridge
